#pragma once

class SelectedKiWaTimeSeriesElements;
class SelectedHbvTimeSeriesElements;
class ParametersGeneral;
class TotalReservoirStorage;
class ModelControl;
class SubCatchment;
class DateTime;
class Glacier;
class HbvAquifer;
class KwaAquifer;
class Lake;

class DistributedElement
{
public:
    DistributedElement();
    ~DistributedElement();
    void SetGeoIndex(int value);
    int GetGeoIndex() const;
    void SetLandIndex(int value);
    int GetLandIndex() const;
    void SetXCoord(double value);
    double GetXCoord() const; 
    void SetYCoord(double value);
    double GetYCoord() const;
    void SetLakeNumber(int value);
    int GetLakeNumber() const;
    void AllocateInputValues(int value);
    int GetNumberInputValues() const;
    void SetInputValue(int i, double value);
    double GetInputValue(int i) const;
    void SetArea(double value);
    double GetArea() const;
    void SetElevation(double value);
    double GetElevation() const;
    void SetSlopeLength(double value);
    double GetSlopeLength() const;
    void SetSlopeAngle(double value);
    double GetSlopeAngle() const;
    void SetAspect(double value);
    double GetAspect() const;
    void SetFlowDirection(int value);
    int GetFlowDirection() const;
    void SetTravelTime(double value);
    double GetTravelTime() const;
    void SetSelectedKiWaTimeSeriesElements(SelectedKiWaTimeSeriesElements *object);
    SelectedKiWaTimeSeriesElements *GetSelectedKiWaTimeSeriesElements() const;
    void SetSelectedHbvTimeSeriesElements(SelectedHbvTimeSeriesElements *object);
    SelectedHbvTimeSeriesElements *GetSelectedHbvTimeSeriesElements() const;
    void SetGeneralPar(ParametersGeneral *parObj);
    ParametersGeneral *GetGeneralPar() const;
    void SetTotalReservoir(TotalReservoirStorage *resObj);
    TotalReservoirStorage *GetTotalReservoir() const;
    void SetModelControlObj(ModelControl *controlObj);
    ModelControl *GetModelControlObj() const;
    void SetPrecipitationCorrection(double value);
    double GetPrecipitationCorrection() const;
    void SetTemperatureCorrection(double value);
    double GetTemperatureCorrection() const;
    void SetNumUpLand(int value);
    int GetNumUpLand() const;
    void SetUpLandFlow(int k, DistributedElement *theElement);
    DistributedElement *GetUpLandFlow(int k) const;
    void SetNextElement(DistributedElement *theElement);
    DistributedElement *GetNextElement() const;
    void SetNextGlacierElement(DistributedElement *theElement);
    DistributedElement *GetNextGlacierElement() const;
    void SetSubCatchmentElement(SubCatchment *theElement);
    SubCatchment *GetSubCatchmentElement() const;
    void SetLake(Lake *theLake);
    Lake *GetLake() const;
    void SetGlacier(Glacier *theGlacier);
    Glacier *GetGlacier() const;
    void SetHbvAquifer(HbvAquifer *theHbvAquifer);
    HbvAquifer *GetHbvAquifer() const;
    void SetKwaAquifer(KwaAquifer *theKwaAquifer);
    KwaAquifer *GetKwaAquifer() const;
    void SetPrecStationsWeightedElevation(double value);
    double GetPrecStationsWeightedElevation();
    void SetTempStationsWeightedElevation(double value);
    double GetTempStationsWeightedElevation();
    void AllocateMetSeries(int numberPrecSeries, int numberTempSeries);
    void SetMetSeriesNumber(int k, int number);
    void SetMetSeriesWeight(int k, double weight);
    int GetMetSeriesNumber(int k);
    double GetMetSeriesWeight(int k);
    void AllocateKiWaWaterBalance(int numberTimeSteps);
    void AllocateHbvWaterBalance(int numberTimeSteps);
    void SetDistributedElementPrecipitation(int index, double value);
    double GetDistributedElementPrecipitation(int index) const;
    void SetDistributedElementTemperature(int index, double value);
    double GetDistributedElementTemperature(int index) const;
    void SetDistributedElementLakeStorage(int index, double value);
    double GetDistributedElementLakeStorage(int index) const;
    void SetDistributedElementSnowStore(int index, double value);
    double GetDistributedElementSnowStore(int index) const;
    void SetDistributedElementSnowCoverFraction(int index, double value);
    double GetDistributedElementSnowCoverFraction(int index) const;
    void SetDistributedElementMeltWater(int index, double value);
    double GetDistributedElementMeltWater(int index) const;
    void SetDistributedElementSnowWaterEquivalentChange(int index, double value);
    double GetDistributedElementSnowWaterEquivalentChange(int index) const;
    void SetDistributedElementWaterOutput(int index, double value);
    double GetDistributedElementWaterOutput(int index) const;
    void SetDistributedElementGlacierSnowStore(int index, double value);
    double GetDistributedElementGlacierSnowStore(int index) const;
    void SetDistributedElementGlacierSnowMeltWater(int index, double value);
    double GetDistributedElementGlacierSnowMeltWater(int index) const;
    void SetDistributedElementGlacierMassBalance(int index, double value);
    double GetDistributedElementGlacierMassBalance(int index) const;
    void SetDistributedElementAreaGlacierMassBalance(int index, double value);
    double GetDistributedElementAreaGlacierMassBalance(int index) const;
    void SetDistributedElementGlacierIceMelt(int index, double value);
    double GetDistributedElementGlacierIceMelt(int index) const;
    void SetDistributedElementAnnualMassBalance(int index, double value);
    double GetDistributedElementAnnualMassBalance(int index) const;
    void SetDistributedElementGlacierIceVolume(int index, double value);
    double GetDistributedElementGlacierIceVolume(int index) const;
    void SetDistributedElementEvapotranspiration(int index, double value);
    double GetDistributedElementEvapotranspiration(int index) const;
    void SetDistributedElementRunoff(int index, double value);
    double GetDistributedElementRunoff(int index) const;
    void SetDistributedElementUpperRunoff(int index, double value);
    double GetDistributedElementUpperRunoff(int index) const;
    void SetDistributedElementLowerRunoff(int index, double value);
    double GetDistributedElementLowerRunoff(int index) const;
    void SetDistributedElementKiWaSoilMoistureOne(int index, double value);
    double GetDistributedElementKiWaSoilMoistureOne(int index) const;
    void SetDistributedElementKiWaSoilMoistureTwo(int index, double value);
    double GetDistributedElementKiWaSoilMoistureTwo(int index) const;
    void SetDistributedElementKiWaGroundWaterDepthOne(int index, double value);
    double GetDistributedElementKiWaGroundWaterDepthOne(int index) const;
    void SetDistributedElementKiWaGroundWaterDepthTwo(int index, double value);
    double GetDistributedElementKiWaGroundWaterDepthTwo(int index) const;
    void SetDistributedElementHbvSoilMoisture(int index, double value);
    double GetDistributedElementHbvSoilMoisture(int index) const;
    void SetDistributedElementHbvSoilMoistureDeficit(int index, double value);
    double GetDistributedElementHbvSoilMoistureDeficit(int index) const;
    void SetDistributedElementHbvPercSoilUpper(int index, double value);
    double GetDistributedElementHbvPercSoilUpper(int index) const;
    void SetDistributedElementHbvUpperZone(int index, double value);
    double GetDistributedElementHbvUpperZone(int index) const;
    void SetDistributedElementHbvLowerZone(int index, double value);
    double GetDistributedElementHbvLowerZone(int index) const;
    void SetAccumulatedDischarge(double upLandValue, double localValue, bool flowHierarchy, bool forceDirect);
    double GetAccumulatedDischarge() const;
    void SetAccumulatedLowerDischarge(double upLandValue, double localValue, bool flowHierarchy, bool forceDirect);
    double GetAccumulatedLowerDischarge() const;
    void SetAccumulatedUpperDischarge(double upLandValue, double localValue, bool flowHierarchy, bool forceDirect);
    double GetAccumulatedUpperDischarge() const;
    void SetAccumulatedSum(double value);
    double GetAccumulatedSum() const;
    void SetAccumulatedSumLake(double value);
    double GetAccumulatedSumLake() const;
    void SetAccumulatedSumSnow(double value);
    double GetAccumulatedSumSnow() const;
    void SetAccumulatedSumGlacier(double value);
    double GetAccumulatedSumGlacier() const;
    void SetAccumulatedSumHbv(double value);
    double GetAccumulatedSumHbv() const;
    void SetAccumulatedPrecipitation(double value);
    double GetAccumulatedPrecipitation() const;
    void SetAccumulatedTemperature(double value);
    double GetAccumulatedTemperature() const;
    void SetAccumulatedLakeStorage(double value);
    double GetAccumulatedLakeStorage() const;
    void SetAccumulatedSnowStore(double value);
    double GetAccumulatedSnowStore() const;
    void SetAccumulatedSnowCoverFraction(double value);
    double GetAccumulatedSnowCoverFraction() const;
    void SetAccumulatedMeltWater(double value);
    double GetAccumulatedMeltWater() const;
    void SetAccumulatedSnowWaterEquivalentChange(double value);
    double GetAccumulatedSnowWaterEquivalentChange() const;
    void SetAccumulatedWaterOutput(double value);
    double GetAccumulatedWaterOutput() const;
    void SetAccumulatedGlacierSnowStore(double value);
    double GetAccumulatedGlacierSnowStore() const;
    void SetAccumulatedGlacierSnowMeltWater(double value);
    double GetAccumulatedGlacierSnowMeltWater() const;
    void SetAccumulatedGlacierMassBalance(double value);
    double GetAccumulatedGlacierMassBalance() const;
    void SetAccumulatedAreaGlacierMassBalance(double value);
    double GetAccumulatedAreaGlacierMassBalance() const;
    void SetAccumulatedGlacierIceMelt(double value);
    double GetAccumulatedGlacierIceMelt() const;
    void SetAccumulatedAnnualMassBalance(double value);
    double GetAccumulatedAnnualMassBalance() const;
    void SetAccumulatedGlacierIceVolume(double value);
    double GetAccumulatedGlacierIceVolume() const;
    void SetAccumulatedEvapotranspiration(double value);
    double GetAccumulatedEvapotranspiration() const;
    void SetAccumulatedRunoff(double value);
    double GetAccumulatedRunoff() const;
    void SetAccumulatedUpperRunoff(double value);
    double GetAccumulatedUpperRunoff() const;
    void SetAccumulatedLowerRunoff(double value);
    double GetAccumulatedLowerRunoff() const;
    void SetAccumulatedHbvSoilMoisture(double value);
    double GetAccumulatedHbvSoilMoisture() const;
    void SetAccumulatedHbvSoilMoistureDeficit(double value);
    double GetAccumulatedHbvSoilMoistureDeficit() const;
    void SetAccumulatedHbvPercSoilUpper(double value);
    double GetAccumulatedHbvPercSoilUpper() const;
    void SetAccumulatedHbvUpperZone(double value);
    double GetAccumulatedHbvUpperZone() const;
    void SetAccumulatedHbvLowerZone(double value);
    double GetAccumulatedHbvLowerZone() const;
    void SetThisYearAnnualGlacierValues(DateTime datetime);
    int GetNumberSum() const;
    void SetSumWaterBalance();
    void SetInitialStorage();
    double GetInitialStorage() const;
    void SetFinalStorage();
    double GetFinalStorage() const;
    double GetSumPrecipitation() const;
    double GetSumEvapotranspiration() const;
    double GetSumRunoff() const;
    void SnowToGlacierIce();
    void RemoveSnowOnGlacierIce();
    void SetAnnualMassBalance(double value);
    void SetSnowStore(double value);
    void SetSubSurfaceHbvStore(double sm, double uz, double lz);
    double GetLandArea() const;
    double GetLakeArea() const;
    double GetGlacierArea() const;
    double GetGlacierIceArea() const;
    double GetKiWaArea() const;
    double GetHbvArea() const;
    // Algorithm to be performed in case: no input to landscape element from upstream elements
    //  void WaterBalance(int timeStep) const;
    // Algorithm to be performed in case: input to landscape element from upstream elements
    void WaterBalance(int timeStep, int initialTimeSteps, int numberTimeSteps, double upLandAccumulatedLowerDischarge, double upLandAccumulatedUpperDischarge) const;
    double GetPrecipitation() const;
    double GetTemperature() const;
    double GetLakeStorage() const;
    double GetLakeStorageChange() const;
    double GetSnowStore() const;
    double GetSnowCoverFraction() const;
    double GetMeltWater() const;
    double GetSnowWaterEquivalentChange() const;
    double GetWaterOutput() const;
    double GetGlacierSnowStore() const;
    double GetGlacierSnowMeltWater() const;
    double GetGlacierMassBalance() const;
    double GetAreaGlacierMassBalance() const;
    double GetGlacierIceMelt() const;
    double GetAnnualMassBalance() const;
    double GetGlacierIceThickness() const;
    double GetGlacierIceVolume() const;
    double GetGlacierSurfaceElevation() const;
    double GetKiWaSoilMoisture(double lengthFraction) const;
    double GetKiWaGroundWaterDepth(double lengthFraction) const;
    double GetHbvSoilMoisture() const;
    double GetHbvSoilMoistureDeficit() const;
    double GetHbvPercSoilUpper() const;
    double GetHbvUpperZone() const;
    double GetHbvLowerZone() const;
    double GetEvapotranspiration() const;
    double GetInterceptionLoss() const;
    double GetTranspSoilEvap() const;
    double GetLakeEvap() const;
    double GetRunoff() const;
    double GetLowerRunoff() const;
    double GetUpperRunoff() const;
    double GetDischarge() const;
    double GetLowerDischarge() const;
    double GetUpperDischarge() const;
    void SetTotalReservoirStorage(int timeStep, int initialTimeSteps, int numberTimeSteps, bool * inputDataFound, bool * firstTotal);

private:
    int geoIndex;
    int landIndex;
    int lakeNumber;
    int numUpLand;
    int numberInputValues;
    int flowDirection;
    int numberSum;
    double xCoord;
    double yCoord;
    double initialStorage;
    double finalStorage;
    double sumPrecipitation;
    double sumEvapotranspiration;
    double sumRunoff;
    double * inputArray;
    double accumulatedSum;
    double accumulatedSumLake;
    double accumulatedSumSnow;
    double accumulatedSumGlacier;
    double accumulatedSumHbv;
    double area;
    double elevation;
    double slopeLength;
    double slopeAngle;
    double aspect;
    double travelTime;
    double precipitationCorrection;
    double temperatureCorrection;
    double accumulatedDischarge;
    double accumulatedLowerDischarge;
    double accumulatedUpperDischarge;
    double accumulatedPrecipitation;
    double accumulatedTemperature;
    double accumulatedLakeStorage;
    double accumulatedSnowStore;
    double accumulatedSnowCoverFraction;
    double accumulatedMeltWater;
    double accumulatedSnowWaterEquivalentChange;
    double accumulatedWaterOutput;
    double accumulatedGlacierSnowStore;
    double accumulatedGlacierSnowMeltWater;
    double accumulatedGlacierMassBalance;
    double accumulatedAreaGlacierMassBalance;
    double accumulatedGlacierIceMelt;
    double accumulatedAnnualMassBalance;
    double accumulatedGlacierIceVolume;
    double accumulatedEvapotranspiration;
    double accumulatedRunoff;
    double accumulatedUpperRunoff;
    double accumulatedLowerRunoff;
    double *distributedElementKiWaSoilMoistureOne;
    double *distributedElementKiWaSoilMoistureTwo;
    double *distributedElementKiWaGroundWaterDepthOne;
    double *distributedElementKiWaGroundWaterDepthTwo;
    double accumulatedHbvSoilMoisture;
    double accumulatedHbvSoilMoistureDeficit;
    double accumulatedHbvPercSoilUpper;
    double accumulatedHbvUpperZone;
    double accumulatedHbvLowerZone;
    double precStationsWeightedElevation;
    double tempStationsWeightedElevation;
    int * metSeriesNumber;
    double * metSeriesWeight;
    double *distributedElementPrecipitation;
    double *distributedElementTemperature;
    double *distributedElementLakeStorage;
    double *distributedElementSnowStore;
    double *distributedElementSnowCoverFraction;
    double *distributedElementMeltWater;
    double *distributedElementSnowWaterEquivalentChange;
    double *distributedElementWaterOutput;
    double *distributedElementGlacierSnowStore;           
    double *distributedElementGlacierSnowMeltWater;           
    double *distributedElementGlacierMassBalance;
    double *distributedElementAreaGlacierMassBalance;
    double *distributedElementGlacierIceMelt;
    double *distributedElementAnnualMassBalance;
    double *distributedElementGlacierIceVolume;
    double *distributedElementEvapotranspiration;
    double *distributedElementRunoff;
    double *distributedElementUpperRunoff;
    double *distributedElementLowerRunoff;
    double *distributedElementHbvSoilMoisture;
    double *distributedElementHbvSoilMoistureDeficit;
    double *distributedElementHbvPercSoilUpper;
    double *distributedElementHbvUpperZone;
    double *distributedElementHbvLowerZone;
    DistributedElement **upLandFlow;
    DistributedElement *nextElement;
    DistributedElement *nextGlacierElement;
    SubCatchment *subCatchmentElement;
    Lake *lake;
    Glacier *glacier;
    HbvAquifer *hbvAquifer;
    KwaAquifer *kwaAquifer;
    SelectedKiWaTimeSeriesElements *selectedKiWaElements;
    SelectedHbvTimeSeriesElements *selectedHbvElements;
    ParametersGeneral *commonPar;
    TotalReservoirStorage * totalReservoir;
    ModelControl * modelControlObject;
};
