#pragma once
class ParametersGeneral
{
public:
    ParametersGeneral();
    ~ParametersGeneral();
    void SetSECONDS_TIMESTEP(int value);
    int GetSECONDS_TIMESTEP() const;
    void SetNUM_PREC_SERIES(int value);
    int GetNUM_PREC_SERIES() const;
    void SetNUM_TEMP_SERIES(int value);
    int GetNUM_TEMP_SERIES() const;
    void SetPREC_GRAD_LOW(double value);
    double GetPREC_GRAD_LOW() const;
    void SetPREC_GRAD_HIGH(double value);
    double GetPREC_GRAD_HIGH() const;
    void SetGRAD_CHANGE_ALT(double value);
    double GetGRAD_CHANGE_ALT() const;
    void SetPREC_CORR_RAIN(double value);
    double GetPREC_CORR_RAIN() const;
    void SetPREC_CORR_SNOW(double value);
    double GetPREC_CORR_SNOW() const;
    void SetLAPSE_DRY(double value);
    double GetLAPSE_DRY() const;
    void SetLAPSE_WET(double value);
    double GetLAPSE_WET() const;
    void SetDAY_TEMP_MEMORY(double value);
    double GetDAY_TEMP_MEMORY() const;
    void SetLAKE_EPOT_PAR(double value);
    double GetLAKE_EPOT_PAR() const;
    void SetKLAKE(double value);
    double GetKLAKE() const;
    void SetDELTA_LEVEL(double value);
    double GetDELTA_LEVEL() const;
    void SetNLAKE(double value);
    double GetNLAKE() const;
    void SetMAXIMUM_LEVEL(double value);
    double GetMAXIMUM_LEVEL() const;
    void SetDENSITY_ICE(double value);
    double GetDENSITY_ICE() const;
    void SetINITIAL_SOIL_MOISTURE(double value);
    double GetINITIAL_SOIL_MOISTURE() const;
    void SetINITIAL_UPPER_ZONE(double value);
    double GetINITIAL_UPPER_ZONE() const;
    void SetINITIAL_LOWER_ZONE(double value);
    double GetINITIAL_LOWER_ZONE() const;
    void SetINITIAL_SATURATED_ONE(double value);
    double GetINITIAL_SATURATED_ONE() const;
    void SetINITIAL_SATURATED_TWO(double value);
    double GetINITIAL_SATURATED_TWO() const;
    void SetINITIAL_LAKE_TEMP(double value);
    double GetINITIAL_LAKE_TEMP() const;
    void SetINITIAL_LAKE_LEVEL(double value);
    double GetINITIAL_LAKE_LEVEL() const;
    void SetINITIAL_SNOW(double value);
    double GetINITIAL_SNOW() const;
    void SetINITIAL_TOTAL_RESERVOIR(double value);
    double GetINITIAL_TOTAL_RESERVOIR();
    void SetDAY_SNOW_ZERO(int value);
    int GetDAY_SNOW_ZERO() const;
    void SetDAY_ANNUAL_GLACIER(int value);
    int GetDAY_ANNUAL_GLACIER() const;

private:
    int SECONDS_TIMESTEP;
    int NUM_PREC_SERIES;
    int NUM_TEMP_SERIES;
    int DAY_SNOW_ZERO;
    int DAY_ANNUAL_GLACIER;
    double PREC_GRAD_LOW;
    double PREC_GRAD_HIGH;
    double GRAD_CHANGE_ALT;
    double PREC_CORR_RAIN;
    double PREC_CORR_SNOW;
    double LAPSE_DRY;
    double LAPSE_WET;
    double DAY_TEMP_MEMORY;
    double LAKE_EPOT_PAR;
    double KLAKE;
    double DELTA_LEVEL;
    double NLAKE;
    double MAXIMUM_LEVEL;
    double DENSITY_ICE;
    double INITIAL_SOIL_MOISTURE;
    double INITIAL_UPPER_ZONE;
    double INITIAL_LOWER_ZONE;
    double INITIAL_SATURATED_ONE;
    double INITIAL_SATURATED_TWO;
    double INITIAL_LAKE_TEMP;
    double INITIAL_LAKE_LEVEL;
    double INITIAL_SNOW;
    double INITIAL_TOTAL_RESERVOIR;
};
