#pragma once

class DateTime;
class DistributedElement;
class SelectedSubCatchmentTimeSeriesElements;

class SubCatchment
{
public:
    SubCatchment();
    ~SubCatchment();
    void SetSubCatchmentIndex(int value);
    int GetSubCatchmentIndex() const;
    void SetIdentifier(int value);
    int GetIdentifier() const;
    void SetNumUpStream(int value);
    int GetNumUpStream() const;
    void SetUpStream(int k, SubCatchment *theSubCatchment);
    SubCatchment *GetUpStream(int k) const;
    void SetNumLandScape(int value);
    int GetNumLandScape() const;
    void SetLandScapeElement(DistributedElement *theElement);
    DistributedElement *GetLandScapeElement() const;
    void SetLakeNumber(int value);
    int GetLakeNumber() const;
    void SetSelectedSubCatchmentTimeSeriesElements(SelectedSubCatchmentTimeSeriesElements *object);
    SelectedSubCatchmentTimeSeriesElements *GetSelectedSubCatchmentTimeSeriesElements() const;
    void SetCorrection(double value);
    double GetCorrection() const;
    void SetManning(double value);
    double GetManning() const;
    void SetRiverSlope(double value);
    double GetRiverSlope() const;
    void SetWidth(double value);
    double GetWidth() const;
    void SetAccumulatedRouteInput(double value);;
    double GetAccumulatedRouteInput() const;
    void AllocateAccumulatedDischarge(int numberTimeSteps);
    void SetAccumulatedDischarge(int index, double value);
    double GetAccumulatedDischarge(int index) const;
    void SetAccumulatedUpperDischarge(int index, double value);
    double GetAccumulatedUpperDischarge(int index) const;
    void SetAccumulatedLowerDischarge(int index, double value);
    double GetAccumulatedLowerDischarge(int index) const;
    void AllocateAccumulatedInFlow(int numberTimeSteps);
    void SetAccumulatedInFlow(int index, double value);
    double GetAccumulatedInFlow(int index) const;
    //  void SetAccumulatedUpperInFlow(int index, double value);
    //  double GetAccumulatedUpperInFlow(int index) const;
    //  void SetAccumulatedLowerInFlow(int index, double value);
    //  double GetAccumulatedLowerInFlow(int index) const;
    void AllocateAccumulatedWaterBalance(int numberTimeSteps);
    void AllocateWaterBalance(int numberTimeSteps);
    void SetAccumulatedPrecipitation(int index, double value);
    double GetAccumulatedPrecipitation(int index) const;
    void SetAccumulatedTemperature(int index, double value);
    double GetAccumulatedTemperature(int index) const;
    void SetAccumulatedLakeStorage(int index, double value);
    double GetAccumulatedLakeStorage(int index) const;
    void SetAccumulatedSnowStore(int index, double value);
    double GetAccumulatedSnowStore(int index) const;
    void SetAccumulatedSnowCoverFraction(int index, double value);
    double GetAccumulatedSnowCoverFraction(int index) const;
    void SetAccumulatedMeltWater(int index, double value);
    double GetAccumulatedMeltWater(int index) const;
    void SetAccumulatedSnowWaterEquivalentChange(int index, double value);
    double GetAccumulatedSnowWaterEquivalentChange(int index) const;
    void SetAccumulatedWaterOutput(int index, double value);
    double GetAccumulatedWaterOutput(int index) const;
    void SetAccumulatedGlacierSnowStore(int index, double value);
    double GetAccumulatedGlacierSnowStore(int index) const;
    void SetAccumulatedGlacierSnowMeltWater(int index, double value);
    double GetAccumulatedGlacierSnowMeltWater(int index) const;
    void SetAccumulatedGlacierMassBalance(int index, double value);
    double GetAccumulatedGlacierMassBalance(int index) const;
    void SetAccumulatedAreaGlacierMassBalance(int index, double value);
    double GetAccumulatedAreaGlacierMassBalance(int index) const;
    void SetAccumulatedGlacierIceMelt(int index, double value);
    double GetAccumulatedGlacierIceMelt(int index) const;
    void SetAccumulatedAnnualMassBalance(int index, double value);
    double GetAccumulatedAnnualMassBalance(int index) const;
    void SetAccumulatedGlacierIceVolume(int index, double value);
    double GetAccumulatedGlacierIceVolume(int index) const;
    void SetAccumulatedEvapotranspiration(int index, double value);
    double GetAccumulatedEvapotranspiration(int index) const;
    void SetAccumulatedRunoff(int index, double value);
    double GetAccumulatedRunoff(int index) const;
    void SetAccumulatedUpperRunoff(int index, double value);
    double GetAccumulatedUpperRunoff(int index) const;
    void SetAccumulatedLowerRunoff(int index, double value);
    double GetAccumulatedLowerRunoff(int index) const;
    void SetAccumulatedHbvSoilMoisture(int index, double value);
    double GetAccumulatedHbvSoilMoisture(int index) const;
    void SetAccumulatedHbvSoilMoistureDeficit(int index, double value);
    double GetAccumulatedHbvSoilMoistureDeficit(int index) const;
    void SetAccumulatedHbvPercSoilUpper(int index, double value);
    double GetAccumulatedHbvPercSoilUpper(int index) const;
    void SetAccumulatedHbvUpperZone(int index, double value);
    double GetAccumulatedHbvUpperZone(int index) const;
    void SetAccumulatedHbvLowerZone(int index, double value);
    double GetAccumulatedHbvLowerZone(int index) const;
    void SetAccumulatedSum(int index, double value);
    double GetAccumulatedSum(int index) const;
    void SetAccumulatedSumLake(int index, double value);
    double GetAccumulatedSumLake(int index) const;
    void SetAccumulatedSumSnow(int index, double value);
    double GetAccumulatedSumSnow(int index) const;
    void SetAccumulatedSumGlacier(int index, double value);
    double GetAccumulatedSumGlacier(int index) const;
    void SetAccumulatedSumHbv(int index, double value);
    double GetAccumulatedSumHbv(int index) const;
    void SetSubCatchmentPrecipitation(int index, double value);
    double GetSubCatchmentPrecipitation(int index) const;
    void SetSubCatchmentTemperature(int index, double value);
    double GetSubCatchmentTemperature(int index) const;
    void SetSubCatchmentLakeStorage(int index, double value);
    double GetSubCatchmentLakeStorage(int index) const;
    void SetSubCatchmentSnowStore(int index, double value);
    double GetSubCatchmentSnowStore(int index) const;
    void SetSubCatchmentSnowCoverFraction(int index, double value);
    double GetSubCatchmentSnowCoverFraction(int index) const;
    void SetSubCatchmentMeltWater(int index, double value);
    double GetSubCatchmentMeltWater(int index) const;
    void SetSubCatchmentSnowWaterEquivalentChange(int index, double value);
    double GetSubCatchmentSnowWaterEquivalentChange(int index) const;
    void SetSubCatchmentWaterOutput(int index, double value);
    double GetSubCatchmentWaterOutput(int index) const;
    void SetSubCatchmentGlacierSnowStore(int index, double value);
    double GetSubCatchmentGlacierSnowStore(int index) const;
    void SetSubCatchmentGlacierSnowMeltWater(int index, double value);
    double GetSubCatchmentGlacierSnowMeltWater(int index) const;
    void SetSubCatchmentGlacierMassBalance(int index, double value);
    double GetSubCatchmentGlacierMassBalance(int index) const;
    void SetSubCatchmentAreaGlacier(int index, double value);
    double GetSubCatchmentAreaGlacier(int index) const;
    void SetSubCatchmentAreaGlacierMassBalance(int index, double value);
    double GetSubCatchmentAreaGlacierMassBalance(int index) const;
    void SetSubCatchmentGlacierIceMelt(int index, double value);
    double GetSubCatchmentGlacierIceMelt(int index) const;
    void SetSubCatchmentAnnualMassBalance(int index, double value);
    double GetSubCatchmentAnnualMassBalance(int index) const;
    void SetSubCatchmentGlacierIceVolume(int index, double value);
    double GetSubCatchmentGlacierIceVolume(int index) const;
    void SetSubCatchmentEvapotranspiration(int index, double value);
    double GetSubCatchmentEvapotranspiration(int index) const;
    void SetSubCatchmentRunoff(int index, double value);
    double GetSubCatchmentRunoff(int index) const;
    void SetSubCatchmentUpperRunoff(int index, double value);
    double GetSubCatchmentUpperRunoff(int index) const;
    void SetSubCatchmentLowerRunoff(int index, double value);
    double GetSubCatchmentLowerRunoff(int index) const;
    void SetSubCatchmentHbvSoilMoisture(int index, double value);
    double GetSubCatchmentHbvSoilMoisture(int index) const;
    void SetSubCatchmentHbvSoilMoistureDeficit(int index, double value);
    double GetSubCatchmentHbvSoilMoistureDeficit(int index) const;
    void SetSubCatchmentHbvPercSoilUpper(int index, double value);
    double GetSubCatchmentHbvPercSoilUpper(int index) const;
    void SetSubCatchmentHbvUpperZone(int index, double value);
    double GetSubCatchmentHbvUpperZone(int index) const;
    void SetSubCatchmentHbvLowerZone(int index, double value);
    double GetSubCatchmentHbvLowerZone(int index) const;
    void ObsDataInput(DateTime firstTime, DateTime lastTime, int numberTimeSteps, int secondsPerTimeStep);
    double GetObsData(int index) const;

private:
    int subCatchmentIndex;
    int identifier;
    int lakeNumber;
    int numUpStream;
    int numLandScape;
    double correction;
    double manning;
    double riverSlope;
    double width;
    double accumulatedRouteInput;
    double *accumulatedDischarge;
    double *accumulatedUpperDischarge;
    double *accumulatedLowerDischarge;
    double *accumulatedInFlow;
    //  double *accumulatedUpperInFlow;
    //  double *accumulatedLowerInFlow;
    double *accumulatedPrecipitation;
    double *accumulatedTemperature;
    double *accumulatedLakeStorage;
    double *accumulatedSnowStore;
    double *accumulatedSnowCoverFraction;
    double *accumulatedMeltWater;
    double *accumulatedSnowWaterEquivalentChange;
    double *accumulatedWaterOutput;
    double *accumulatedGlacierSnowStore;
    double *accumulatedGlacierSnowMeltWater;
    double *accumulatedGlacierMassBalance;
    double *accumulatedAreaGlacierMassBalance;
    double *accumulatedGlacierIceMelt;
    double *accumulatedAnnualMassBalance;
    double *accumulatedGlacierIceVolume;
    double *accumulatedEvapotranspiration;
    double *accumulatedRunoff;
    double *accumulatedUpperRunoff;
    double *accumulatedLowerRunoff;
    double *accumulatedHbvSoilMoisture;
    double *accumulatedHbvSoilMoistureDeficit;
    double *accumulatedHbvPercSoilUpper;
    double *accumulatedHbvUpperZone;
    double *accumulatedHbvLowerZone;
    double *accumulatedSum;
    double *accumulatedSumLake;
    double *accumulatedSumSnow;
    double *accumulatedSumGlacier;
    double *accumulatedSumHbv;
    double *subCatchmentPrecipitation;
    double *subCatchmentTemperature;
    double *subCatchmentLakeStorage;
    double *subCatchmentSnowStore;
    double *subCatchmentSnowCoverFraction;
    double *subCatchmentMeltWater;
    double *subCatchmentSnowWaterEquivalentChange;
    double *subCatchmentWaterOutput;
    double *subCatchmentGlacierSnowStore;           
    double *subCatchmentGlacierSnowMeltWater;           
    double *subCatchmentGlacierMassBalance;
    double *subCatchmentAreaGlacier;
    double *subCatchmentAreaGlacierMassBalance;
    double *subCatchmentGlacierIceMelt;
    double *subCatchmentAnnualMassBalance;
    double *subCatchmentGlacierIceVolume;
    double *subCatchmentEvapotranspiration;
    double *subCatchmentRunoff;
    double *subCatchmentUpperRunoff;
    double *subCatchmentLowerRunoff;
    double *subCatchmentHbvSoilMoisture;
    double *subCatchmentHbvSoilMoistureDeficit;
    double *subCatchmentHbvPercSoilUpper;
    double *subCatchmentHbvUpperZone;
    double *subCatchmentHbvLowerZone;
    double *observedData;
    SubCatchment **UpStream;
    DistributedElement *landScapeElement;
    SelectedSubCatchmentTimeSeriesElements *selectedSubCatchmentElements;
};
